### ISSUE TITLE
Menu items disappear

### ISSUE THREAD

**Issue by janno42** [fsr-itse/1327#118]
When selecting a document menu item on the second level, it disappears together with all the others on the second level, because the parent item in the first level is no longer selected.

"Main Page" selected:
![mainpage](https://cloud.githubusercontent.com/assets/1781719/7238945/65401a26-e7a6-11e4-9d7a-051c0958dc25.PNG)

"Test page" (in the second level) selected:
![testpage](https://cloud.githubusercontent.com/assets/1781719/7238951/73e7e66c-e7a6-11e4-9644-29f6db621081.PNG)

**Comment by janno42** [comment]
please continue or at least give us your current state ;)

**Comment by PFischbeck** [comment]
My current progress can be seen at b10359fd8 (on my own fork). Feel free to use it, I didn't write any tests for it yet.
