### ISSUE TITLE
Minutes

### ISSUE THREAD

**Issue by janno42** [fsr-itse/1327#2]
The page needs a place to hold minutes.

Minutes have at least the following:
- name
- date
- participants
- writer
- content (formatted in *Markdown*)
- ~~state (published or unpublished)~~
- _new:_ `intern` flag

*EDIT:* still needed:

- [x]  there should be a publish / unpublish button if the protocol is not internal -> this adds view rights to anonymous 
- [x] there should be an automatic unpublished label
- [x]  in the create / edit form there should be a checkbox to set the state to internal
- [x]  in the create / edit form there should be an option to set tags
- [x] the date should be visible somewhere
- [x] the date must also be visible on the minutes list page
- [ ] show tags on minute page

**Comment by invliD** [comment]
name = document.title
writer = document.author
content = document.text

**Comment by Nef10** [comment]
- [ ]  permissions should not be visible in the menu
- [ ]  instead there should be a publish / unpublish button if the protocol is not internal
- [ ]  in the create / edit form there should be a checkbox to set the state to internal
- [ ]  in the create / edit form there should be an option to set tags
- [ ] the date should be visible somewhere

**Comment by janno42** [comment]
- [ ] the date must also be visible on the minutes list page
