### ISSUE TITLE
Create nice buttons for markdown creating in editor

### ISSUE THREAD

**Issue by Bartzi** [fsr-itse/1327#43]
We should add some buttons to the editor. 
Clicking a button adds markdown code to the written text.
We need buttons for:
* headings
* images
* code
* ...

**Comment by Nef10** [comment]
I would suggest https://github.com/toopay/bootstrap-markdown

**Comment by invliD** [comment]
me likey.

**Comment by Bartzi** [comment]
nice :smile_cat: go for it: :+1:
