### ISSUE TITLE
Display message if no minutes are available

### ISSUE THREAD

**Issue by cmfcmf** [fsr-itse/1327#591]
I'm always confused when I click the link sent by email to view the latest FSR protocols and I'm greeted with an empty page with no indication on what's wrong:
![image](https://user-images.githubusercontent.com/2145092/29141992-b7a94a20-7d50-11e7-8a7e-98ddfd548d9a.png)

Well, you need to login to view them - but it always takes me a few seconds to realize that.

**Comment by janno42** [comment]
The user has the permission to see the page, otherwise an error message would be shown.
What is asked here is a message like `No minutes available. You might have to login first.`
