### ISSUE TITLE
minutes page is blank when not logged in

### ISSUE THREAD

**Issue by karyon** [fsr-itse/1327#603]
accessing the minutes page from an external network, it looks like this:

![2017-10-02 23_10_21-myhpi protokolle - firefox developer edition](https://user-images.githubusercontent.com/1891915/31099658-0ab59296-a7c7-11e7-887c-08c9dc4cb83a.png)

that's not helpful :)

**Comment by janno42** [comment]
i'm certain i already talked about this with someone else, but obviously that alone wasn't the solution ;)
thanks for opening the ticket.

**Comment by janno42** [comment]
okay, now i found it. was already fixed in 064113278c828b5601ad0573fe8409e3e408eec9
